word_bank = [
    {
        "id": "dog",
        "japanese": "犬",
        "english": "Dog",
        "audio": "audio/words/dog.mp3",
        "accepted": ["犬", "いぬ", "イヌ"],
    },
    {
        "id": "cat",
        "japanese": "猫",
        "english": "Cat",
        "audio": "audio/words/cat.mp3",
        "accepted": ["猫", "ねこ", "ネコ"],
    },
    {
        "id": "water",
        "japanese": "水",
        "english": "Water",
        "audio": "audio/words/water.mp3",
        "accepted": ["水", "みず", "ミズ"],
    },
    {
        "id": "book",
        "japanese": "本",
        "english": "Book",
        "audio": "audio/words/book.mp3",
        "accepted": ["本", "ほん", "ホン"],
    },
    {
        "id": "car",
        "japanese": "車",
        "english": "Car",
        "audio": "audio/words/car.mp3",
        "accepted": ["車", "くるま", "クルマ"],
    },
    {
        "id": "friend",
        "japanese": "友達",
        "english": "Friend",
        "audio": "audio/words/friend.mp3",
        "accepted": ["友達", "ともだち", "トモダチ"],
    },
    {
        "id": "house",
        "japanese": "家",
        "english": "House",
        "audio": "audio/words/house.mp3",
        "accepted": ["家", "いえ", "イエ", "うち", "ウチ"],
    },
    {
        "id": "time",
        "japanese": "時間",
        "english": "Time",
        "audio": "audio/words/time.mp3",
        "accepted": ["時間", "じかん", "ジカン"],
    },
    {
        "id": "food",
        "japanese": "食べ物",
        "english": "Food",
        "audio": "audio/words/food.mp3",
        "accepted": ["食べ物", "たべもの", "タベモノ"],
    },
    {
        "id": "drink",
        "japanese": "飲み物",
        "english": "Drink",
        "audio": "audio/words/drink.mp3",
        "accepted": ["飲み物", "のみもの", "ノミモノ"],
    },
    {
        "id": "to_eat",
        "japanese": "食べる",
        "english": "To eat",
        "audio": "audio/words/to_eat.mp3",
        "accepted": ["食べる", "たべる", "タベル"],
    },
    {
        "id": "to_drink",
        "japanese": "飲む",
        "english": "To drink",
        "audio": "audio/words/to_drink.mp3",
        "accepted": ["飲む", "のむ", "ノム"],
    },
    {
        "id": "to_go",
        "japanese": "行く",
        "english": "To go",
        "audio": "audio/words/to_go.mp3",
        "accepted": ["行く", "いく", "イク"],
    },
    {
        "id": "to_see",
        "japanese": "見る",
        "english": "To see / watch",
        "audio": "audio/words/to_see.mp3",
        "accepted": ["見る", "みる", "ミル"],
    },
    {
        "id": "to_speak",
        "japanese": "話す",
        "english": "To speak",
        "audio": "audio/words/to_speak.mp3",
        "accepted": ["話す", "はなす", "ハナス"],
    },
    {
        "id": "big",
        "japanese": "大きい",
        "english": "Big",
        "audio": "audio/words/big.mp3",
        "accepted": ["大きい", "おおきい", "オオキイ"],
    },
    {
        "id": "small",
        "japanese": "小さい",
        "english": "Small",
        "audio": "audio/words/small.mp3",
        "accepted": ["小さい", "ちいさい", "チイサイ"],
    },
    {
        "id": "delicious",
        "japanese": "美味しい",
        "english": "Delicious",
        "audio": "audio/words/delicious.mp3",
        "accepted": ["美味しい", "おいしい", "オイシイ"],
    },
    {
        "id": "fun",
        "japanese": "楽しい",
        "english": "Fun",
        "audio": "audio/words/fun.mp3",
        "accepted": ["楽しい", "たのしい", "タノシイ"],
    },
    {
        "id": "good",
        "japanese": "良い",
        "english": "Good",
        "audio": "audio/words/good.mp3",
        "accepted": ["良い", "いい", "よい", "イイ", "ヨイ"],
    },
]


phrase_bank = [
    {
        "id": "hello",
        "japanese": "こんにちは",
        "english": "Hello / Good afternoon",
        "audio": "audio/phrases/hello.mp3",
        "accepted": ["こんにちは", "コンニチハ"],
    },
    {
        "id": "good_morning",
        "japanese": "おはようございます",
        "english": "Good morning",
        "audio": "audio/phrases/good_morning.mp3",
        "accepted": ["おはようございます", "オハヨウゴザイマス"],
    },
    {
        "id": "good_evening",
        "japanese": "こんばんは",
        "english": "Good evening",
        "audio": "audio/phrases/good_evening.mp3",
        "accepted": ["こんばんは", "コンバンハ"],
    },
    {
        "id": "thank_you",
        "japanese": "ありがとう",
        "english": "Thank you",
        "audio": "audio/phrases/thank_you.mp3",
        "accepted": ["ありがとう", "アリガトウ"],
    },
    {
        "id": "thank_you_very_much",
        "japanese": "ありがとうございます",
        "english": "Thank you very much",
        "audio": "audio/phrases/thank_you_very_much.mp3",
        "accepted": ["ありがとうございます", "アリガトウゴザイマス"],
    },
    {
        "id": "excuse_me",
        "japanese": "すみません",
        "english": "Excuse me / I'm sorry",
        "audio": "audio/phrases/excuse_me.mp3",
        "accepted": ["すみません", "スミマセン"],
    },
    {
        "id": "im_sorry",
        "japanese": "ごめんなさい",
        "english": "I'm sorry",
        "audio": "audio/phrases/im_sorry.mp3",
        "accepted": ["ごめんなさい", "ゴメンナサイ"],
    },
    {
        "id": "yes",
        "japanese": "はい",
        "english": "Yes",
        "audio": "audio/phrases/yes.mp3",
        "accepted": ["はい", "ハイ"],
    },
    {
        "id": "no",
        "japanese": "いいえ",
        "english": "No",
        "audio": "audio/phrases/no.mp3",
        "accepted": ["いいえ", "イイエ"],
    },
    {
        "id": "how_are_you",
        "japanese": "お元気ですか",
        "english": "How are you?",
        "audio": "audio/phrases/how_are_you.mp3",
        "accepted": ["お元気ですか", "おげんきですか", "オゲンキデスカ"],
    },
    {
        "id": "nice_to_meet_you",
        "japanese": "はじめまして",
        "english": "Nice to meet you",
        "audio": "audio/phrases/nice_to_meet_you.mp3",
        "accepted": ["はじめまして", "ハジメマシテ"],
    },
    {
        "id": "goodbye",
        "japanese": "さようなら",
        "english": "Goodbye",
        "audio": "audio/phrases/goodbye.mp3",
        "accepted": ["さようなら", "サヨウナラ"],
    },
    {
        "id": "itadakimasu",
        "japanese": "いただきます",
        "english": "Thank you for the meal (before eating)",
        "audio": "audio/phrases/itadakimasu.mp3",
        "accepted": ["いただきます", "イタダキマス"],
    },
    {
        "id": "gochisosama",
        "japanese": "ごちそうさまでした",
        "english": "Thank you for the meal (after eating)",
        "audio": "audio/phrases/gochisosama.mp3",
        "accepted": ["ごちそうさまでした", "ゴチソウサマデシタ"],
    },
    {
        "id": "how_much_is_it",
        "japanese": "いくらですか",
        "english": "How much is it?",
        "audio": "audio/phrases/how_much_is_it.mp3",
        "accepted": ["いくらですか", "イクラデスカ"],
    },
    {
        "id": "i_dont_understand",
        "japanese": "わかりません",
        "english": "I don't understand",
        "audio": "audio/phrases/i_dont_understand.mp3",
        "accepted": ["わかりません", "分かりません", "ワカリマセン"],
    },
    {
        "id": "please_help_me",
        "japanese": "助けてください",
        "english": "Please help me",
        "audio": "audio/phrases/please_help_me.mp3",
        "accepted": ["助けてください", "たすけてください", "タスケテクダサイ"],
    },
    {
        "id": "can_you_speak_english",
        "japanese": "英語を話せますか",
        "english": "Can you speak English?",
        "audio": "audio/phrases/can_you_speak_english.mp3",
        "accepted": ["英語を話せますか", "えいごをはなせますか", "エイゴヲハナセマスカ"],
    },
]